name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  indexer:
    name: Indexer
    uses: jimmydrinkscoffee/niall-monorepo/.github/workflows/docker.yaml@main
    with:
      context: .
      file: ./apps/indexer/Dockerfile
      tag: vbphung/niall-indexer
    secrets: inherit
